# Generated by Django 4.2.1 on 2023-09-27 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_specialty_options_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cert',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name': 'Identity', 'verbose_name_plural': 'Identities'},
        ),
        migrations.AlterModelOptions(
            name='langs',
            options={'verbose_name': 'Language Spoken', 'verbose_name_plural': 'Languages Spoken'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='identity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
