# Generated by Django 4.2.1 on 2023-09-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cert_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Langs',
            new_name='Lang',
        ),
    ]
