# Generated by Django 5.1.4 on 2024-12-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_langtype_point_remove_lang_lang1_remove_lang_lang2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='freelancer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
