# Generated by Django 5.1.4 on 2024-12-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_client_alter_customuser_freelancer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='freelancer',
            new_name='agent',
        ),
    ]
