# Generated by Django 5.1.4 on 2024-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_freelancer_customuser_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='point',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Cert',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
