# Generated by Django 5.1.4 on 2025-02-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_cert_user_remove_employment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='agent',
            new_name='recruiter',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='client',
            new_name='staff',
        ),
    ]
