# Generated by Django 5.1.4 on 2025-02-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_agent_customuser_recruiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
