# Generated by Django 5.1.4 on 2025-02-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_gallery_remove_post_images_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='videos',
            new_name='video',
        ),
    ]
