# Generated by Django 5.1.4 on 2025-02-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_rename_videos_post_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('name',), 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(),
        ),
    ]
