# Generated by Django 5.1.4 on 2025-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(),
        ),
    ]
