# Generated by Django 5.1.4 on 2025-02-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='gallery',
        ),
    ]
