# Generated by Django 5.1.4 on 2025-02-20 11:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_rename_image_post_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
