# Generated by Django 5.1.4 on 2025-02-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
