# Generated by Django 5.1.4 on 2025-02-25 03:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
