# Generated by Django 5.1.4 on 2025-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_alter_post_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='discipline',
        ),
        migrations.AddField(
            model_name='post',
            name='discipline',
            field=models.ManyToManyField(default=1, related_name='post_discipline', to='docs.discipline'),
        ),
    ]
