# Generated by Django 5.1.4 on 2025-02-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_remove_post_discipline_post_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discipline',
            field=models.ManyToManyField(related_name='post_discipline', to='docs.discipline'),
        ),
    ]
