# Generated by Django 5.1.4 on 2025-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
