# Generated by Django 5.1.4 on 2025-02-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_alter_discipline_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
