# Generated by Django 5.1.4 on 2025-02-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_alter_discipline_name'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.ManyToManyField(related_name='post_country', to='regions.state'),
        ),
    ]
