# Generated by Django 5.1.4 on 2025-02-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_remove_post_state_post_state'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=0, verbose_name=((0, 'Draft'), (1, 'Published'), (2, 'Featured'))),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.ManyToManyField(related_name='post_region', to='regions.state'),
        ),
    ]
