# Generated by Django 5.1.4 on 2025-02-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0017_post_status_alter_post_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Featured')], default=0),
        ),
    ]
