# Generated by Django 5.1.4 on 2025-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0018_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Featured')], default=0),
        ),
    ]
